# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: 2022年 8月 2日 星期二 23时03分44秒 CST
#
#/ usage: jayce-public/git:sync [ --directory <>] [ --remote <origin>] [ --target <>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
#
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    unrecognized_args=()

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in
            --directory) rerun_option_check $# $1; DIRECTORY=$2 ; shift 2 ;;
            --remote) rerun_option_check $# $1; REMOTE=$2 ; shift 2 ;;
            --target) rerun_option_check $# $1; TARGET=$2 ; shift 2 ;;
            # help option
            -\?|--help)
                rerun_option_usage
                exit 2
                ;;
            # unrecognized arguments
            *)
              unrecognized_args+=("$OPT")
              shift
              ;;
        esac
    done

    # Set defaultable options.
    [[ -z "$REMOTE" ]] && REMOTE="$(rerun_property_get $RERUN_MODULE_DIR/options/remote DEFAULT)"
    # Check required options are set

    # If option variables are declared exportable, export them.

    # Make unrecognized command line options available in $_CMD_LINE
    if [ ${#unrecognized_args[@]} -gt 0 ]; then
      export _CMD_LINE="${unrecognized_args[@]}"
    fi
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${DIRECTORY:=}
: ${REMOTE:=}
: ${TARGET:=}
# Default command line to null if not set
: ${_CMD_LINE:=}


