#!/usr/bin/env bash

#/ command: git:push: "git push script command."
#/ usage: rerun git:push [ --remote <origin>] [ --branch <>] [ --directory <>] 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: REMOTE BRANCH DIRECTORY

. "$RERUN_MODULE_DIR/lib/functions.sh" "push" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

gitDirectory=$(getCurrentDirPathByName "$DIRECTORY")
remote=$REMOTE
branch=$(getCurrentBranchByName "$BRANCH")

rerun_include_sh "$RERUN_MODULE_DIR/commands/push/main.sh"

# Done. Exit with last command exit status.
exit $?

