# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: 2022年 7月 6日 星期三 22时41分49秒 CST
#
#/ usage: jayce-public/download:image  --link <> [ --config <>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
#
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    unrecognized_args=()

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in
            --link) rerun_option_check $# $1; LINK=$2 ; shift 2 ;;
            --config) rerun_option_check $# $1; CONFIG=$2 ; shift 2 ;;
            # help option
            -\?|--help)
                rerun_option_usage
                exit 2
                ;;
            # unrecognized arguments
            *)
              unrecognized_args+=("$OPT")
              shift
              ;;
        esac
    done

    # Set defaultable options.

    # Check required options are set
    [[ -z "$LINK" ]] && { echo >&2 "missing required option: --link" ; return 2 ; }
    # If option variables are declared exportable, export them.

    # Make unrecognized command line options available in $_CMD_LINE
    if [ ${#unrecognized_args[@]} -gt 0 ]; then
      export _CMD_LINE="${unrecognized_args[@]}"
    fi
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${LINK:=}
: ${CONFIG:=}
# Default command line to null if not set
: ${_CMD_LINE:=}


