# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: 2022年 6月28日 星期二 23时39分03秒 CST
#
#/ usage: jayce-public/git:checkout 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
#
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_check_include_common_function() {
    common_dir=$(dirname $RERUN_MODULE_DIR)
    common_function_dir="${common_dir}/common/function"
    if [ -d $common_function_dir ]; then
        rerun_include_dir_sh $common_function_dir
    fi
    return 0
}
rerun_options_parse() {

    unrecognized_args=()

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in

            # help option
            -\?|--help)
                rerun_option_usage
                exit 2
                ;;
            # unrecognized arguments
            *)
              unrecognized_args+=("$OPT")
              shift
              ;;
        esac
    done

    # Set defaultable options.

    # Check required options are set

    # If option variables are declared exportable, export them.

    # Make unrecognized command line options available in $_CMD_LINE
    if [ ${#unrecognized_args[@]} -gt 0 ]; then
      export _CMD_LINE="${unrecognized_args[@]}"
    fi
    #
    return 0
}


# If not already set, initialize the options variables to null.

# Default command line to null if not set
: ${_CMD_LINE:=}


