#!/usr/bin/env bash

. "$RERUN_MODULE_DIR/lib/functions.sh" "checkout" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

. "$RERUN_MODULE_DIR/commands/checkout/main.sh" || {
  echo >&2 "Failed loading main.sh file." ; exit 1 ;
}

exit $?

