#!/usr/bin/env bash

#/ command: service:nginx: "nginx service."
#/ usage: rerun service:nginx [ --action <start>]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ACTION

. "$RERUN_MODULE_DIR/lib/functions.sh" "nginx" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

serviceShortName='nginx'
serviceName='nginx'
moduleCommonDir=$(dirname $RERUN_MODULE_DIR)
moduleCommonDir="${moduleCommonDir}/common/runtime"
cacheFilePath="${moduleCommonDir}/cache/.service.cache"
servicePathCacheKey='SERVICE_NGINX_PATH'

rerun_include_sh "$RERUN_MODULE_DIR/commands/nginx/main.sh"

# Done. Exit with last command exit status.
exit $?

